package skyrave;

import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fml.common.registry.GameRegistry;
import skyrave.block.SkyraveBlocks;
import skyrave.item.SkyraveItems;



public class Recipes {
    public static void addRecipes() {
        // 3 Amber Ore:
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BRONZE_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.BRONZE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BRONZE_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.BRONZE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BRONZE_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.BRONZE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BRONZE_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.BRONZE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BRONZE_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.BRONZE_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BRONZE_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.BRONZE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BRONZE_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.BRONZE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BRONZE_BOOTS , 1),"A A","A A", 'A', SkyraveItems.BRONZE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BRONZE_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.BRONZE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMETHYST_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.AMETHYST_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMETHYST_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.AMETHYST_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMETHYST_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.AMETHYST_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMETHYST_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.AMETHYST_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMETHYST_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.AMETHYST_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMETHYST_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.AMETHYST_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMETHYST_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.AMETHYST_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMETHYST_BOOTS , 1),"A A","A A", 'A', SkyraveItems.AMETHYST_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMETHYST_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.AMETHYST_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BERYL_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.BERYL_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BERYL_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.BERYL_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BERYL_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.BERYL_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BERYL_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.BERYL_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BERYL_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.BERYL_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BERYL_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.BERYL_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BERYL_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.BERYL_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BERYL_BOOTS , 1),"A A","A A", 'A', SkyraveItems.BERYL_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BERYL_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.BERYL_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMBER_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.AMBER_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMBER_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.AMBER_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMBER_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.AMBER_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMBER_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.AMBER_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMBER_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.AMBER_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMBER_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.AMBER_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMBER_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.AMBER_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMBER_BOOTS , 1),"A A","A A", 'A', SkyraveItems.AMBER_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.AMBER_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.AMBER_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TANZANITE_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.TANZANITE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TANZANITE_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.TANZANITE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TANZANITE_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.TANZANITE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TANZANITE_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.TANZANITE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TANZANITE_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.TANZANITE_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TANZANITE_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.TANZANITE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TANZANITE_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.TANZANITE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TANZANITE_BOOTS , 1),"A A","A A", 'A', SkyraveItems.TANZANITE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TANZANITE_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.TANZANITE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PERIDOT_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.PERIDOT_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PERIDOT_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.PERIDOT_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PERIDOT_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.PERIDOT_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PERIDOT_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.PERIDOT_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PERIDOT_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.PERIDOT_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PERIDOT_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.PERIDOT_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PERIDOT_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.PERIDOT_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PERIDOT_BOOTS , 1),"A A","A A", 'A', SkyraveItems.PERIDOT_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PERIDOT_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.PERIDOT_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SILVER_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.SILVER_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SILVER_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.SILVER_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SILVER_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.SILVER_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SILVER_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.SILVER_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SILVER_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.SILVER_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SILVER_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.SILVER_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SILVER_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.SILVER_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SILVER_BOOTS , 1),"A A","A A", 'A', SkyraveItems.SILVER_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SILVER_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.SILVER_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOURMALINE_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.TOURMALINE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOURMALINE_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.TOURMALINE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOURMALINE_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.TOURMALINE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOURMALINE_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.TOURMALINE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOURMALINE_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.TOURMALINE_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOURMALINE_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.TOURMALINE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOURMALINE_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.TOURMALINE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOURMALINE_BOOTS , 1),"A A","A A", 'A', SkyraveItems.TOURMALINE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOURMALINE_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.TOURMALINE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.ZIRCON_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.ZIRCON_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.ZIRCON_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.ZIRCON_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.ZIRCON_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.ZIRCON_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.ZIRCON_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.ZIRCON_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.ZIRCON_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.ZIRCON_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.ZIRCON_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.ZIRCON_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.ZIRCON_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.ZIRCON_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.ZIRCON_BOOTS , 1),"A A","A A", 'A', SkyraveItems.ZIRCON_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.ZIRCON_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.ZIRCON_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOPAZ_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.TOPAZ_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOPAZ_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.TOPAZ_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOPAZ_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.TOPAZ_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOPAZ_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.TOPAZ_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOPAZ_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.TOPAZ_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOPAZ_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.TOPAZ_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOPAZ_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.TOPAZ_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOPAZ_BOOTS , 1),"A A","A A", 'A', SkyraveItems.TOPAZ_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.TOPAZ_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.TOPAZ_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CITRINE_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.CITRINE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CITRINE_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.CITRINE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CITRINE_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.CITRINE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CITRINE_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.CITRINE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CITRINE_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.CITRINE_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CITRINE_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.CITRINE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CITRINE_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.CITRINE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CITRINE_BOOTS , 1),"A A","A A", 'A', SkyraveItems.CITRINE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CITRINE_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.CITRINE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CORDIERITE_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.CORDIERITE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CORDIERITE_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.CORDIERITE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CORDIERITE_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.CORDIERITE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CORDIERITE_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.CORDIERITE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CORDIERITE_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.CORDIERITE_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CORDIERITE_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.CORDIERITE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CORDIERITE_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.CORDIERITE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CORDIERITE_BOOTS , 1),"A A","A A", 'A', SkyraveItems.CORDIERITE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CORDIERITE_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.CORDIERITE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.GARNET_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.GARNET_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.GARNET_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.GARNET_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.GARNET_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.GARNET_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.GARNET_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.GARNET_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.GARNET_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.GARNET_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.GARNET_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.GARNET_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.GARNET_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.GARNET_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.GARNET_BOOTS , 1),"A A","A A", 'A', SkyraveItems.GARNET_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.GARNET_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.GARNET_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SAPPHIRE_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.SAPPHIRE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SAPPHIRE_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.SAPPHIRE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SAPPHIRE_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.SAPPHIRE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SAPPHIRE_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.SAPPHIRE_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SAPPHIRE_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.SAPPHIRE_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SAPPHIRE_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.SAPPHIRE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SAPPHIRE_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.SAPPHIRE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SAPPHIRE_BOOTS , 1),"A A","A A", 'A', SkyraveItems.SAPPHIRE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.SAPPHIRE_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.SAPPHIRE_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.RUBY_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.RUBY_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.RUBY_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.RUBY_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.RUBY_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.RUBY_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.RUBY_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.RUBY_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.RUBY_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.RUBY_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.RUBY_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.RUBY_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.RUBY_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.RUBY_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.RUBY_BOOTS , 1),"A A","A A", 'A', SkyraveItems.RUBY_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.RUBY_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.RUBY_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.EMERALD_AXE , 1)," AA"," BA"," B ", 'A' , Items.emerald, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.EMERALD_SHOVEL , 1)," A "," B "," B ", 'A' , Items.emerald, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.EMERALD_PICKAXE , 1),"AAA"," B ", " B ", 'A' , Items.emerald, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.EMERALD_HOE , 1)," AA"," B "," B ", 'A' , Items.emerald, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.EMERALD_SWORD , 1)," A "," A "," B ", 'A' , Items.emerald, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.EMERALD_HELMET , 1),"AAA","A A", 'A' , Items.emerald);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.EMERALD_LEGGINGS , 1),"AAA","A A","A A", 'A' , Items.emerald);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.EMERALD_BOOTS , 1),"A A","A A", 'A', Items.emerald);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.EMERALD_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , Items.emerald);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PLATINUM_AXE , 1)," AA"," BA"," B ", 'A' , SkyraveItems.PLATINUM_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PLATINUM_SHOVEL , 1)," A "," B "," B ", 'A' , SkyraveItems.PLATINUM_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PLATINUM_PICKAXE , 1),"AAA"," B ", " B ", 'A' , SkyraveItems.PLATINUM_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PLATINUM_HOE , 1)," AA"," B "," B ", 'A' , SkyraveItems.PLATINUM_INGOT, 'B', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PLATINUM_SWORD , 1)," A "," A "," B ", 'A' , SkyraveItems.PLATINUM_INGOT, 'B',Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PLATINUM_HELMET , 1),"AAA","A A", 'A' , SkyraveItems.PLATINUM_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PLATINUM_LEGGINGS , 1),"AAA","A A","A A", 'A' , SkyraveItems.PLATINUM_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PLATINUM_BOOTS , 1),"A A","A A", 'A', SkyraveItems.PLATINUM_INGOT);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PLATINUM_CHESTPLATE , 1),"A A","AAA","AAA", 'A' , SkyraveItems.PLATINUM_INGOT);



        GameRegistry.addRecipe(new ItemStack(SkyraveItems.APPLE_PIE , 3),"AB", 'A' , Items.apple, 'B', SkyraveItems.DOUGH);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CARAMEL_APPLE , 3),"AB", 'A' , Items.apple, 'B', SkyraveItems.CARAMEL);

        GameRegistry.addRecipe(new ItemStack(SkyraveItems.DAIKON_OSHINKO_MAKI, 3), "A", "B","C",'A',SkyraveItems.RICE,'B',SkyraveItems.RADISH,'C',SkyraveItems.WEED );
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.EGG_ROLL_SUSHI, 3), "A", "B", "C", 'A', Items.egg, 'B', SkyraveItems.RICE, 'C', SkyraveItems.WEED);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CHEESEBURGER, 3), "XAX", "XBX", "XCX", 'X', SkyraveItems.SLICE_OF_BREAD, 'A', SkyraveItems.CHEESE, 'B', SkyraveItems.SALAD, 'C', Items.beef);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.HOTDOG, 3), "XAX", "XBX", "XXX", 'X', SkyraveItems.SLICE_OF_BREAD, 'A', SkyraveItems.MUSTARD, 'B', SkyraveItems.SAUSAGE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BANANA_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.BANANA, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CHERRY_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.CHERRY, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CHOCOLATE_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.CHOCOLATE, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CRANBERRY_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.CRANBERRY, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.GREEN_GRAPE_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.GREEN_GRAPES, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.KIWI_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.KIWI, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.LEMON_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.LEMON, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.LIME_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.LIME, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.MANGO_ICE_CREAM, 3), "A", "B","C",'A',SkyraveItems.MANGO,'B',SkyraveItems.GELATIN,'C',SkyraveItems.CONE );
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.ORANGE_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.ORANGE, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PEER_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.PEER, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PINEAPPLE_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.PINEAPPLE, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PISTACHIO_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.PISTACHIO, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PURPLE_GRAPE_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.PURPLE_GRAPES, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.RAISIN_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.RAISIN, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.RASPBERRY_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.RASPBERRY, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.STRAWBERRY_ICE_CREAM, 3), "A", "B", "C", 'A', SkyraveItems.STRAWBERRY, 'B', SkyraveItems.GELATIN, 'C', SkyraveItems.CONE);

        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BANANA_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.BANANA, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CHERRY_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.CHERRY, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CHOCOLATE_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.CHOCOLATE, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.CRANBERRY_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.CRANBERRY, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.GREEN_GRAPE_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.GREEN_GRAPES, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.KIWI_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.KIWI, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.LEMON_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.LEMON, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.LIME_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.LIME, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.MANGO_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.MANGO, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.ORANGE_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.ORANGE, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PEER_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.PEER, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PINEAPPLE_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.PINEAPPLE, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PISTACHIO_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.PISTACHIO, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.PURPLE_GRAPE_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.PURPLE_GRAPES, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.RAISIN_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.RAISIN, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.RASPBERRY_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.RASPBERRY, 'B', SkyraveItems.GELATIN, 'C', Items.stick);
        GameRegistry.addRecipe(new ItemStack(SkyraveItems.STRAWBERRY_LOLLIPOP, 3), "A", "B", "C", 'A', SkyraveItems.STRAWBERRY, 'B', SkyraveItems.GELATIN, 'C', Items.stick);


        GameRegistry.addRecipe(new ItemStack(SkyraveItems.BOWL_OF_SALAD, 3), "A", "B","C", 'A',SkyraveItems.SALAD,'B',SkyraveItems.TOMATO,'C',Items.bowl );
        
        GameRegistry.addShapelessRecipe(new ItemStack(SkyraveItems.SHAVED_ICE, 1), Blocks.ice);
        GameRegistry.addShapelessRecipe(new ItemStack(SkyraveItems.CONE, 1), SkyraveItems.DOUGH);

        GameRegistry.addSmelting(SkyraveBlocks.AMBER_ORE, new ItemStack (SkyraveItems.AMBER_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.AMETHYST_ORE, new ItemStack (SkyraveItems.AMETHYST_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.BERYL_ORE, new ItemStack (SkyraveItems.BERYL_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.CITRINE_ORE, new ItemStack (SkyraveItems.CITRINE_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.COPPER_ORE, new ItemStack (SkyraveItems.COPPER_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.CORDIERITE_ORE, new ItemStack (SkyraveItems.CORDIERITE_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.GARNET_ORE, new ItemStack (SkyraveItems.GARNET_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.PERIDOT_ORE, new ItemStack (SkyraveItems.PERIDOT_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.PLATINUM_ORE, new ItemStack (SkyraveItems.PLATINUM_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.RUBY_ORE, new ItemStack (SkyraveItems.RUBY_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.SAPPHIRE_ORE, new ItemStack (SkyraveItems.SAPPHIRE_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.SILVER_ORE, new ItemStack (SkyraveItems.SILVER_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.TANZANITE_ORE, new ItemStack (SkyraveItems.TANZANITE_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.TIN_ORE, new ItemStack (SkyraveItems.TIN_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.TOPAZ_ORE, new ItemStack (SkyraveItems.TOPAZ_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.TOURMALINE_ORE, new ItemStack (SkyraveItems.TOURMALINE_INGOT),1 );
        GameRegistry.addSmelting(SkyraveBlocks.ZIRCON_ORE, new ItemStack (SkyraveItems.ZIRCON_INGOT),1 );
        GameRegistry.addSmelting(SkyraveItems.BACON_RAW, new ItemStack (SkyraveItems.BACON_COOKED),1 );
        GameRegistry.addSmelting(Items.sugar, new ItemStack (SkyraveItems.CARAMEL),1 );
        GameRegistry.addSmelting(SkyraveItems.UNCOOKED_CALAMARI, new ItemStack (SkyraveItems.COOKED_CALAMARI),1 );
        GameRegistry.addSmelting(Items.egg, new ItemStack (SkyraveItems.BOILED_EGG),1 );
        GameRegistry.addSmelting(SkyraveItems.CORN, new ItemStack (SkyraveItems.GRILLED_CORN),1 );
        GameRegistry.addSmelting(Items.bone, new ItemStack (SkyraveItems.GELATIN),1 );



    }
}
