package skyrave.item;


import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.potion.Potion;
import net.minecraftforge.common.util.EnumHelper;
import skyrave.Skyrave;
import skyrave.SkyraveCreativeTabs;
import skyrave.block.SkyraveBlocks;

public class SkyraveItems {


    public static final Item AMBER_INGOT = new ItemSkyrave().setUnlocalizedName("ingotAmber");
    public static final Item AMETHYST_INGOT = new ItemSkyrave().setUnlocalizedName("ingotAmethyst");
    public static final Item BERYL_INGOT = new ItemSkyrave().setUnlocalizedName("ingotBeryl");
    public static final Item BRONZE_INGOT = new ItemSkyrave().setUnlocalizedName("ingotBronze");
    public static final Item CITRINE_INGOT = new ItemSkyrave().setUnlocalizedName("ingotCitrine");
    public static final Item COPPER_INGOT = new ItemSkyrave().setUnlocalizedName("ingotCopper");
    public static final Item CORDIERITE_INGOT = new ItemSkyrave().setUnlocalizedName("ingotCordierite");
    public static final Item GARNET_INGOT = new ItemSkyrave().setUnlocalizedName("ingotGarnet");
    public static final Item PERIDOT_INGOT = new ItemSkyrave().setUnlocalizedName("ingotPeridot");
    public static final Item PLATINUM_INGOT = new ItemSkyrave().setUnlocalizedName("ingotPlatinum");
    public static final Item RUBY_INGOT = new ItemSkyrave().setUnlocalizedName("ingotRuby");
    public static final Item SAPPHIRE_INGOT = new ItemSkyrave().setUnlocalizedName("ingotSapphire");
    public static final Item SILVER_INGOT = new ItemSkyrave().setUnlocalizedName("ingotSilver");
    public static final Item TANZANITE_INGOT = new ItemSkyrave().setUnlocalizedName("ingotTanzanite");
    public static final Item TIN_INGOT = new ItemSkyrave().setUnlocalizedName("ingotTin");
    public static final Item TOPAZ_INGOT = new ItemSkyrave().setUnlocalizedName("ingotTopaz");
    public static final Item TOURMALINE_INGOT = new ItemSkyrave().setUnlocalizedName("ingotTourmaline");
    public static final Item ZIRCON_INGOT = new ItemSkyrave().setUnlocalizedName("ingotZircon");


    public static final Item.ToolMaterial BRONZE = EnumHelper.addToolMaterial("bronze",1,150,4.0F,1.0F,6);
    public static final Item.ToolMaterial AMETHYST = EnumHelper.addToolMaterial("amethyst",1,170,4.4F,1.1F,7);
    public static final Item.ToolMaterial BERYL = EnumHelper.addToolMaterial("beryl",1,190,4.8F,1.2F,8);
    public static final Item.ToolMaterial AMBER = EnumHelper.addToolMaterial("amber",1,210,5.2F,1.4F,9);
    public static final Item.ToolMaterial TANZANITE= EnumHelper.addToolMaterial("tanzanite",1,230,5.6F,1.6F,10);
    public static final Item.ToolMaterial PERIDOT = EnumHelper.addToolMaterial("amber",1,250,6.0F,1.8F,11);
    public static final Item.ToolMaterial SILVER = EnumHelper.addToolMaterial("amber",2,300,6.4F,2.0F,12);
    public static final Item.ToolMaterial TOURMALINE= EnumHelper.addToolMaterial("amber",2,350,6.5F,2.1F,13);
    public static final Item.ToolMaterial ZIRCON = EnumHelper.addToolMaterial("amber",2,400,6.6F,2.2F,14);
    public static final Item.ToolMaterial TOPAZ = EnumHelper.addToolMaterial("amber",2,450,6.7F,2.3F,15);
    public static final Item.ToolMaterial CITRINE = EnumHelper.addToolMaterial("amber",2,500,6.8F,2.4F,16);
    public static final Item.ToolMaterial CORDIERITE = EnumHelper.addToolMaterial("amber",2,550,6.9F,2.5F,17);
    public static final Item.ToolMaterial GARNET = EnumHelper.addToolMaterial("amber",3,650,7.1F,2.6F,18);
    public static final Item.ToolMaterial SAPPHIRE = EnumHelper.addToolMaterial("amber",3,850,7.4F,2.7F,19);
    public static final Item.ToolMaterial RUBY = EnumHelper.addToolMaterial("amber",3,1050,7.7F,2.8F,20);
    public static final Item.ToolMaterial EMERALD = EnumHelper.addToolMaterial("amber",3,1300,8.0F,2.9F,21);
    public static final Item.ToolMaterial PLATINIUM = EnumHelper.addToolMaterial("amber",3,2000,10.0F,3.5F,25);


    public static final ItemArmor.ArmorMaterial BRONZE_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("bronzeArmorMaterial", "skyrave:bronze" ,106, new int[]{1,3,2,1},10);
    public static final ItemArmor.ArmorMaterial AMETHYST_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("amethystArmorMaterial", "skyrave:amethyst" ,115, new int[]{1,3,2,1},11);
    public static final ItemArmor.ArmorMaterial BERYL_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("berylArmorMaterial", "skyrave:beryl" ,124, new int[]{1,4,3,1},12);
    public static final ItemArmor.ArmorMaterial AMBER_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("amberArmorMaterial", "skyrave:amber" ,133, new int[]{1,4,3,1},13);
    public static final ItemArmor.ArmorMaterial TANZANITE_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("tanzaniteArmorMaterial", "skyrave:tanzanite" ,142, new int[]{1,5,4,1},14);
    public static final ItemArmor.ArmorMaterial PERIDOT_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("peridotArmorMaterial", "skyrave:peridot" ,151, new int[]{1,5,4,2},16);
    public static final ItemArmor.ArmorMaterial SILVER_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("silverArmorMaterial", "skyrave:silver" ,160, new int[]{1,6,4,2},18);
    public static final ItemArmor.ArmorMaterial TOURMALINE_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("bronzeArmorMaterial", "skyrave:tourmaline" ,180, new int[]{2,6,5,2},20);
    public static final ItemArmor.ArmorMaterial ZIRCON_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("zirconArmorMaterial", "skyrave:zircon" ,200, new int[]{2,6,5,2},22);
    public static final ItemArmor.ArmorMaterial TOPAZ_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("topazArmorMaterial", "skyrave:topaz" ,220, new int[]{2,6,5,2},24);
    public static final ItemArmor.ArmorMaterial CITRINE_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("citrineArmorMaterial", "skyrave:citrine" ,240, new int[]{2,6,5,3},26);
    public static final ItemArmor.ArmorMaterial CORDIERITE_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("cordieriteArmorMaterial", "skyrave:cordierite" ,260, new int[]{2,6,5,3},28);
    public static final ItemArmor.ArmorMaterial GARNET_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("garnetArmorMaterial", "skyrave:garnet" ,280, new int[]{2,6,5,3},30);
    public static final ItemArmor.ArmorMaterial SAPPHIRE_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("sapphireArmorMaterial", "skyrave:sapphire" ,300, new int[]{3,7,6,3},32);
    public static final ItemArmor.ArmorMaterial RUBY_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("rubyArmorMaterial", "skyrave:ruby" ,320, new int[]{3,7,6,3},34);
    public static final ItemArmor.ArmorMaterial EMERALD_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("emeraldArmorMaterial", "skyrave:emerald" ,340, new int[]{3,7,6,3},36);
    public static final ItemArmor.ArmorMaterial PLATINUM_ARMOR_MATERIAL = EnumHelper.addArmorMaterial("platinumArmorMaterial", "skyrave:platinum" ,400, new int[]{4,10,8,4},40);





    public static final Item SHAVED_ICE = new ItemSkyrave().setUnlocalizedName("iceShaved");
    public static final Item DOUGH = new ItemSkyrave().setUnlocalizedName("dough");
    public static final Item WEED = new ItemSkyrave().setUnlocalizedName("weed");
    public static final Item SALT = new ItemSkyrave().setUnlocalizedName("salt");
    public static final Item PEPPER = new ItemSkyrave().setUnlocalizedName("pepper");
    public static final Item TUNA = new ItemSkyrave().setUnlocalizedName("tuna");
    public static final Item RED_TUNA = new ItemSkyrave().setUnlocalizedName("tunaRed");
    public static final Item WASABI = new ItemSkyrave().setUnlocalizedName("wasabi");
    public static final Item UNCOOKED_CALAMARI = new ItemSkyrave().setUnlocalizedName("calamaryUncooked");
    public static final Item MUSTARD = new ItemSkyrave().setUnlocalizedName("mustard");
    public static final Item GELATIN = new ItemSkyrave().setUnlocalizedName("gelatin");

    public static final Item GRAPE_SEEDS = new ItemSeedsSkyrave(SkyraveBlocks.GRAPES).setUnlocalizedName("seedsGrape");
    public static final Item PINEAPPLE_SEEDS = new ItemSeedsSkyrave(SkyraveBlocks.PINEAPPLE).setUnlocalizedName("seedsPineapple");
    public static final Item CORN_SEEDS = new ItemSeedsSkyrave(SkyraveBlocks.CORN).setUnlocalizedName("seedsCorn");
    public static final Item CUCUMBER_SEEDS = new ItemSeedsSkyrave(SkyraveBlocks.CUCUMBER).setUnlocalizedName("seedsCucumber");
    public static final Item ONION_SEEDS = new ItemSeedsSkyrave(SkyraveBlocks.ONION).setUnlocalizedName("seedsOnion");
    public static final Item RADISH_SEEDS = new ItemSeedsSkyrave(SkyraveBlocks.RADISH).setUnlocalizedName("seedsRadish");
    public static final Item SALAD_SEEDS = new ItemSeedsSkyrave(SkyraveBlocks.SALAD).setUnlocalizedName("seedsSalad");
    public static final Item TOMATO_SEEDS = new ItemSeedsSkyrave(SkyraveBlocks.TOMATO).setUnlocalizedName("seedsTomato");

    // Food: foodPoints (2 = 1 bar), saturation, isWolfFood
    public static final Item PURPLE_GRAPES = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("grapesPurple");
    public static final Item GREEN_GRAPES = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("grapesGreen");
    public static final Item PINEAPPLE = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("pineapple");
    public static final Item CORN = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("corn");
    public static final Item CUCUMBER = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("cucumber");
    public static final Item ONION = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("onion");
    public static final Item RADISH = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("radish");
    public static final Item SALAD = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("salad");
    public static final Item TOMATO = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("tomato");
    public static final Item APPLE_PIE = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("pieApple");
    public static final Item BACON_RAW = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("rawBacon");
    public static final Item BACON_COOKED = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("cookedBacon");
    public static final Item BANANA = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("banana");
    public static final Item BLUEBERRY = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("blueberry");
    public static final Item SLICE_OF_BREAD = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("breadSliceof");
    public static final Item BUTTER = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("butter");
    public static final Item CARAMEL = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("caramel");
    public static final Item CHEESE = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("cheese");
    public static final Item CHERRY = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("cherry");
    public static final Item CHILLI = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("chilli");
    public static final Item CHOCOLATE = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("chocolate");
    public static final Item COCONUT = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("coconut");
    public static final Item DONUT = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("donut");
    public static final Item FLOUR = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("flour");
    public static final Item GARLIC = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("garlic");
    public static final Item BANANA_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamBanana");
    public static final Item CHERRY_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamCherry");
    public static final Item CHOCOLATE_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamChocolate");
    public static final Item CRANBERRY_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamCranberry");
    public static final Item GREEN_GRAPE_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamGreengrape");
    public static final Item KIWI_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamKiwi");
    public static final Item LEMON_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamLemon");
    public static final Item LIME_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamLime");
    public static final Item MANGO_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamMango");
    public static final Item ORANGE_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamOrange");
    public static final Item PEER_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamPeer");
    public static final Item PINEAPPLE_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamPineapple");
    public static final Item PISTACHIO_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamPistachio");
    public static final Item PURPLE_GRAPE_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamPurplegrape");
    public static final Item RAISIN_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamRaisin");
    public static final Item RASPBERRY_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamRaspberry");
    public static final Item STRAWBERRY_ICE_CREAM = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("icecreamStrawberry");
    public static final Item BANANA_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopBanana");
    public static final Item CHERRY_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopCherry");
    public static final Item CHOCOLATE_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopChocolate");
    public static final Item CRANBERRY_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopCranberry");
    public static final Item GREEN_GRAPE_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopGreengrape");
    public static final Item KIWI_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopKiwi");
    public static final Item LEMON_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopLemon");
    public static final Item LIME_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopLime");
    public static final Item MANGO_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopMango");
    public static final Item ORANGE_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopOrange");
    public static final Item PEER_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopPeer");
    public static final Item PINEAPPLE_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopPineapple");
    public static final Item PISTACHIO_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopPistachio");
    public static final Item PURPLE_GRAPE_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopPurplegrape");
    public static final Item RAISIN_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopRaisin");
    public static final Item RASPBERRY_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopRaspberry");
    public static final Item STRAWBERRY_LOLLIPOP = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("lollipopStrawberry");
    public static final Item CARAMEL_APPLE = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("appleCaramel");
    public static final Item RICE = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("rice");
    public static final Item FISH_EGGS = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("eggsFish");
    public static final Item BOILED_EGG = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("eggBoiled");
    public static final Item DAIKON_OSHINKO_MAKI = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("makiDaikonoshinko");
    public static final Item EGG_ROLL_SUSHI = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("sushiEggroll");
    public static final Item EGGPLANT = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("eggplant");
    public static final Item MAGURO_NIGIRI_WASABI = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("wasabiNigirimaguro");
    public static final Item MAKI = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("maki");
    public static final Item MANGO_SUSHI = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("sushiMango");
    public static final Item MAGURO_NIGIRI = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("nigiriMaguro");
    public static final Item NIGIRI = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("nigiri");
    public static final Item NIGIRI_WASABI = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("wasabiNigiri");
    public static final Item ONIGIRI = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("onigiri");
    public static final Item ROLL = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("roll");
    public static final Item TEKKAMAKI = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("tekkamaki");
    public static final Item TORO_NIGIRI_TEIYAKI = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("teiyakiNigiritoro");
    public static final Item SASHI_SUSHI = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("sushiSashi");
    public static final Item STRAWBERRY = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("strawberry");
    public static final Item SHRIMP = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("shrimp");
    public static final Item BOWL_OF_SALAD = new ItemFoodSkyrave(3, 0.1F, false).setUnlocalizedName("saladBowlof");
    public static final Item KIWI = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("kiwi");
    public static final Item LEMON = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("lemon");
    public static final Item LIME = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("lime");
    public static final Item MANGO = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("mango");
    public static final Item PEER = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("peer");
    public static final Item COOKED_CALAMARI = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("calamaryCooked");
    public static final Item SQUID = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("squid");
    public static final Item GRILLED_CORN = new ItemFoodSkyrave(2, 0.1F, false).setUnlocalizedName("cornGrilled");
    public static final Item CONE = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("cone");
    public static final Item CHEESEBURGER = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("cheeseburger");
    public static final Item HOTDOG = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("hotdog");
    public static final Item SAUSAGE = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("sausage");
    public static final Item CRANBERRY = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("cranberry");
    public static final Item ORANGE = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("orange");
    public static final Item PISTACHIO = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("pistachio");
    public static final Item RAISIN = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("raisin");
    public static final Item RASPBERRY = new ItemFoodSkyrave(1, 0.1F, false).setUnlocalizedName("raspberry");



    public static final Item BRONZE_PICKAXE= new ItemPickaxeSkyrave (BRONZE).setUnlocalizedName("pickaxeBronze");
    public static final Item AMETHYST_PICKAXE= new ItemPickaxeSkyrave (AMETHYST).setUnlocalizedName("pickaxeAmethyst");
    public static final Item BERYL_PICKAXE= new ItemPickaxeSkyrave (BERYL).setUnlocalizedName("pickaxeBeryl");
    public static final Item AMBER_PICKAXE= new ItemPickaxeSkyrave (AMBER).setUnlocalizedName("pickaxeAmber");
    public static final Item TANZANITE_PICKAXE= new ItemPickaxeSkyrave (TANZANITE).setUnlocalizedName("pickaxeTanzanite");
    public static final Item PERIDOT_PICKAXE= new ItemPickaxeSkyrave (PERIDOT).setUnlocalizedName("pickaxePeridot");
    public static final Item SILVER_PICKAXE= new ItemPickaxeSkyrave (SILVER).setUnlocalizedName("pickaxeSilver");
    public static final Item TOURMALINE_PICKAXE= new ItemPickaxeSkyrave (TOURMALINE).setUnlocalizedName("pickaxeTourmaline");
    public static final Item ZIRCON_PICKAXE= new ItemPickaxeSkyrave (ZIRCON).setUnlocalizedName("pickaxeZircon");
    public static final Item TOPAZ_PICKAXE= new ItemPickaxeSkyrave (TOPAZ).setUnlocalizedName("pickaxeTopaz");
    public static final Item CITRINE_PICKAXE= new ItemPickaxeSkyrave (CITRINE).setUnlocalizedName("pickaxeCitrine");
    public static final Item CORDIERITE_PICKAXE= new ItemPickaxeSkyrave (CORDIERITE).setUnlocalizedName("pickaxeCordierite");
    public static final Item GARNET_PICKAXE= new ItemPickaxeSkyrave (GARNET).setUnlocalizedName("pickaxeGarnet");
    public static final Item SAPPHIRE_PICKAXE= new ItemPickaxeSkyrave (SAPPHIRE).setUnlocalizedName("pickaxeSapphire");
    public static final Item RUBY_PICKAXE= new ItemPickaxeSkyrave (RUBY).setUnlocalizedName("pickaxeRuby");
    public static final Item EMERALD_PICKAXE= new ItemPickaxeSkyrave (EMERALD).setUnlocalizedName("pickaxeEmerald");
    public static final Item PLATINUM_PICKAXE= new ItemPickaxeSkyrave (PLATINIUM).setUnlocalizedName("pickaxePlatinum");

    public static final Item BRONZE_HOE= new ItemHoeSkyrave (BRONZE).setUnlocalizedName("hoeBronze");
    public static final Item AMETHYST_HOE= new ItemHoeSkyrave (AMETHYST).setUnlocalizedName("hoeAmethyst");
    public static final Item BERYL_HOE= new ItemHoeSkyrave (BERYL).setUnlocalizedName("hoeBeryl");
    public static final Item AMBER_HOE= new ItemHoeSkyrave (AMBER).setUnlocalizedName("hoeAmber");
    public static final Item TANZANITE_HOE= new ItemHoeSkyrave (TANZANITE).setUnlocalizedName("hoeTanzanite");
    public static final Item PERIDOT_HOE= new ItemHoeSkyrave (PERIDOT).setUnlocalizedName("hoePeridot");
    public static final Item SILVER_HOE= new ItemHoeSkyrave (SILVER).setUnlocalizedName("hoeSilver");
    public static final Item TOURMALINE_HOE= new ItemHoeSkyrave (TOURMALINE).setUnlocalizedName("hoeTourmaline");
    public static final Item ZIRCON_HOE= new ItemHoeSkyrave (ZIRCON).setUnlocalizedName("hoeZircon");
    public static final Item TOPAZ_HOE= new ItemHoeSkyrave (TOPAZ).setUnlocalizedName("hoeTopaz");
    public static final Item CITRINE_HOE= new ItemHoeSkyrave (CITRINE).setUnlocalizedName("hoeCitrine");
    public static final Item CORDIERITE_HOE= new ItemHoeSkyrave (CORDIERITE).setUnlocalizedName("hoeCordierite");
    public static final Item GARNET_HOE= new ItemHoeSkyrave (GARNET).setUnlocalizedName("hoeGarnet");
    public static final Item SAPPHIRE_HOE= new ItemHoeSkyrave (SAPPHIRE).setUnlocalizedName("hoeSapphire");
    public static final Item RUBY_HOE= new ItemHoeSkyrave (RUBY).setUnlocalizedName("hoeRuby");
    public static final Item EMERALD_HOE= new ItemHoeSkyrave (EMERALD).setUnlocalizedName("hoeEmerald");
    public static final Item PLATINUM_HOE= new ItemHoeSkyrave (PLATINIUM).setUnlocalizedName("hoePlatinum");

    public static final Item BRONZE_AXE= new ItemAxeSkyrave (BRONZE).setUnlocalizedName("axeBronze");
    public static final Item AMETHYST_AXE= new ItemAxeSkyrave (AMETHYST).setUnlocalizedName("axeAmethyst");
    public static final Item BERYL_AXE= new ItemAxeSkyrave (BERYL).setUnlocalizedName("axeBeryl");
    public static final Item AMBER_AXE= new ItemAxeSkyrave (AMBER).setUnlocalizedName("axeAmber");
    public static final Item TANZANITE_AXE= new ItemAxeSkyrave (TANZANITE).setUnlocalizedName("axeTanzanite");
    public static final Item PERIDOT_AXE= new ItemAxeSkyrave (PERIDOT).setUnlocalizedName("axePeridot");
    public static final Item SILVER_AXE= new ItemAxeSkyrave (SILVER).setUnlocalizedName("axeSilver");
    public static final Item TOURMALINE_AXE= new ItemAxeSkyrave (TOURMALINE).setUnlocalizedName("axeTourmaline");
    public static final Item ZIRCON_AXE= new ItemAxeSkyrave (ZIRCON).setUnlocalizedName("axeZircon");
    public static final Item TOPAZ_AXE= new ItemAxeSkyrave (TOPAZ).setUnlocalizedName("axeTopaz");
    public static final Item CITRINE_AXE= new ItemAxeSkyrave (CITRINE).setUnlocalizedName("axeCitrine");
    public static final Item CORDIERITE_AXE= new ItemAxeSkyrave (CORDIERITE).setUnlocalizedName("axeCordierite");
    public static final Item GARNET_AXE= new ItemAxeSkyrave (GARNET).setUnlocalizedName("axeGarnet");
    public static final Item SAPPHIRE_AXE= new ItemAxeSkyrave (SAPPHIRE).setUnlocalizedName("axeSapphire");
    public static final Item RUBY_AXE= new ItemAxeSkyrave (RUBY).setUnlocalizedName("axeRuby");
    public static final Item EMERALD_AXE= new ItemAxeSkyrave (EMERALD).setUnlocalizedName("axeEmerald");
    public static final Item PLATINUM_AXE= new ItemAxeSkyrave (PLATINIUM).setUnlocalizedName("axePlatinum");

    public static final Item BRONZE_SHOVEL= new ItemShovelSkyrave (BRONZE).setUnlocalizedName("shovelBronze");
    public static final Item AMETHYST_SHOVEL= new ItemShovelSkyrave (AMETHYST).setUnlocalizedName("shovelAmethyst");
    public static final Item BERYL_SHOVEL= new ItemShovelSkyrave (BERYL).setUnlocalizedName("shovelBeryl");
    public static final Item AMBER_SHOVEL= new ItemShovelSkyrave (AMBER).setUnlocalizedName("shovelAmber");
    public static final Item TANZANITE_SHOVEL= new ItemShovelSkyrave (TANZANITE).setUnlocalizedName("shovelTanzanite");
    public static final Item PERIDOT_SHOVEL= new ItemShovelSkyrave (PERIDOT).setUnlocalizedName("shovelPeridot");
    public static final Item SILVER_SHOVEL= new ItemShovelSkyrave (SILVER).setUnlocalizedName("shovelSilver");
    public static final Item TOURMALINE_SHOVEL= new ItemShovelSkyrave (TOURMALINE).setUnlocalizedName("shovelTourmaline");
    public static final Item ZIRCON_SHOVEL= new ItemShovelSkyrave (ZIRCON).setUnlocalizedName("shovelZircon");
    public static final Item TOPAZ_SHOVEL= new ItemShovelSkyrave (TOPAZ).setUnlocalizedName("shovelTopaz");
    public static final Item CITRINE_SHOVEL= new ItemShovelSkyrave (CITRINE).setUnlocalizedName("shovelCitrine");
    public static final Item CORDIERITE_SHOVEL= new ItemShovelSkyrave (CORDIERITE).setUnlocalizedName("shovelCordierite");
    public static final Item GARNET_SHOVEL= new ItemShovelSkyrave (GARNET).setUnlocalizedName("shovelGarnet");
    public static final Item SAPPHIRE_SHOVEL= new ItemShovelSkyrave (SAPPHIRE).setUnlocalizedName("shovelSapphire");
    public static final Item RUBY_SHOVEL= new ItemShovelSkyrave (RUBY).setUnlocalizedName("shovelRuby");
    public static final Item EMERALD_SHOVEL= new ItemShovelSkyrave (EMERALD).setUnlocalizedName("shovelEmerald");
    public static final Item PLATINUM_SHOVEL= new ItemShovelSkyrave (PLATINIUM).setUnlocalizedName("shovelPlatinum");

    public static final Item BRONZE_SWORD= new ItemSwordSkyrave (BRONZE).setUnlocalizedName("swordBronze");
    public static final Item AMETHYST_SWORD= new ItemSwordSkyrave (AMETHYST).setUnlocalizedName("swordAmethyst");
    public static final Item BERYL_SWORD= new ItemSwordSkyrave (BERYL).setUnlocalizedName("swordBeryl");
    public static final Item AMBER_SWORD= new ItemSwordSkyrave (AMBER).setUnlocalizedName("swordAmber");
    public static final Item TANZANITE_SWORD= new ItemSwordSkyrave (TANZANITE).setUnlocalizedName("swordTanzanite");
    public static final Item PERIDOT_SWORD= new ItemSwordSkyrave (PERIDOT).setUnlocalizedName("swordPeridot");
    public static final Item SILVER_SWORD= new ItemSwordSkyrave (SILVER).setUnlocalizedName("swordSilver");
    public static final Item TOURMALINE_SWORD= new ItemSwordSkyrave (TOURMALINE).setUnlocalizedName("swordTourmaline");
    public static final Item ZIRCON_SWORD= new ItemSwordSkyrave (ZIRCON).setUnlocalizedName("swordZircon");
    public static final Item TOPAZ_SWORD= new ItemSwordSkyrave (TOPAZ).setUnlocalizedName("swordTopaz");
    public static final Item CITRINE_SWORD= new ItemSwordSkyrave (CITRINE).setUnlocalizedName("swordCitrine");
    public static final Item CORDIERITE_SWORD= new ItemSwordSkyrave (CORDIERITE).setUnlocalizedName("swordCordierite");
    public static final Item GARNET_SWORD= new ItemSwordSkyrave (GARNET).setUnlocalizedName("swordGarnet");
    public static final Item SAPPHIRE_SWORD= new ItemSwordSkyrave (SAPPHIRE).setUnlocalizedName("swordSapphire");
    public static final Item RUBY_SWORD= new ItemSwordSkyrave (RUBY).setUnlocalizedName("swordRuby");
    public static final Item EMERALD_SWORD= new ItemSwordSkyrave (EMERALD).setUnlocalizedName("swordEmerald");
    public static final Item PLATINUM_SWORD= new ItemSwordSkyrave (PLATINIUM).setUnlocalizedName("swordPlatinum");

    public static final Item BRONZE_HELMET= new ItemArmorSkyrave (BRONZE_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetBronze");
    public static final Item BRONZE_CHESTPLATE= new ItemArmorSkyrave (BRONZE_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplateBronze");
    public static final Item BRONZE_LEGGINGS= new ItemArmorSkyrave (BRONZE_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsBronze");
    public static final Item BRONZE_BOOTS= new ItemArmorSkyrave (BRONZE_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsBronze");
    public static final Item AMETHYST_HELMET= new ItemArmorSkyrave (AMETHYST_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetAmethyst");
    public static final Item AMETHYST_CHESTPLATE= new ItemArmorSkyrave (AMETHYST_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplateAmethyst");
    public static final Item AMETHYST_LEGGINGS= new ItemArmorSkyrave (AMETHYST_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsAmethyst");
    public static final Item AMETHYST_BOOTS= new ItemArmorSkyrave (AMETHYST_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsAmethyst");
    public static final Item BERYL_HELMET= new ItemArmorSkyrave (BERYL_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetBeryl");
    public static final Item BERYL_CHESTPLATE= new ItemArmorSkyrave (BERYL_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplateBeryl");
    public static final Item BERYL_LEGGINGS= new ItemArmorSkyrave (BERYL_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsBeryl");
    public static final Item BERYL_BOOTS= new ItemArmorSkyrave (BERYL_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsBeryl");
    public static final Item AMBER_HELMET= new ItemArmorSkyrave (AMBER_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetAmber");
    public static final Item AMBER_CHESTPLATE= new ItemArmorSkyrave (AMBER_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplateAmber");
    public static final Item AMBER_LEGGINGS= new ItemArmorSkyrave (AMBER_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsAmber");
    public static final Item AMBER_BOOTS= new ItemArmorSkyrave (AMBER_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsAmber");
    public static final Item TANZANITE_HELMET= new ItemArmorSkyrave (TANZANITE_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetTanzanite");
    public static final Item TANZANITE_CHESTPLATE= new ItemArmorSkyrave (TANZANITE_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplateTanzanite");
    public static final Item TANZANITE_LEGGINGS= new ItemArmorSkyrave (TANZANITE_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsTanzanite");
    public static final Item TANZANITE_BOOTS= new ItemArmorSkyrave (TANZANITE_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsTanzanite");
    public static final Item PERIDOT_HELMET= new ItemArmorSkyrave (PERIDOT_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetPeridot");
    public static final Item PERIDOT_CHESTPLATE= new ItemArmorSkyrave (PERIDOT_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplatePeridot");
    public static final Item PERIDOT_LEGGINGS= new ItemArmorSkyrave (PERIDOT_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsPeridot");
    public static final Item PERIDOT_BOOTS= new ItemArmorSkyrave (PERIDOT_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsPeridot");
    public static final Item SILVER_HELMET= new ItemArmorSkyrave (SILVER_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetSilver");
    public static final Item SILVER_CHESTPLATE= new ItemArmorSkyrave (SILVER_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplateSilver");
    public static final Item SILVER_LEGGINGS= new ItemArmorSkyrave (SILVER_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsSilver");
    public static final Item SILVER_BOOTS= new ItemArmorSkyrave (SILVER_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsSilver");
    public static final Item TOURMALINE_HELMET= new ItemArmorSkyrave (TOURMALINE_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetTourmaline");
    public static final Item TOURMALINE_CHESTPLATE= new ItemArmorSkyrave (TOURMALINE_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplateTourmaline");
    public static final Item TOURMALINE_LEGGINGS= new ItemArmorSkyrave (TOURMALINE_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsTourmaline");
    public static final Item TOURMALINE_BOOTS= new ItemArmorSkyrave (TOURMALINE_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsTourmaline");
    public static final Item ZIRCON_HELMET= new ItemArmorSkyrave (ZIRCON_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetZircon");
    public static final Item ZIRCON_CHESTPLATE= new ItemArmorSkyrave (ZIRCON_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplateZircon");
    public static final Item ZIRCON_LEGGINGS= new ItemArmorSkyrave (ZIRCON_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsZircon");
    public static final Item ZIRCON_BOOTS= new ItemArmorSkyrave (ZIRCON_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsZircon");
    public static final Item TOPAZ_HELMET= new ItemArmorSkyrave (TOPAZ_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetTopaz");
    public static final Item TOPAZ_CHESTPLATE= new ItemArmorSkyrave (TOPAZ_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplateTopaz");
    public static final Item TOPAZ_LEGGINGS= new ItemArmorSkyrave (TOPAZ_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsTopaz");
    public static final Item TOPAZ_BOOTS= new ItemArmorSkyrave (TOPAZ_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsTopaz");
    public static final Item CITRINE_HELMET= new ItemArmorSkyrave (CITRINE_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetCitrine");
    public static final Item CITRINE_CHESTPLATE= new ItemArmorSkyrave (CITRINE_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplateCitrine");
    public static final Item CITRINE_LEGGINGS= new ItemArmorSkyrave (CITRINE_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsCitrine");
    public static final Item CITRINE_BOOTS= new ItemArmorSkyrave (CITRINE_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsCitrine");
    public static final Item CORDIERITE_HELMET= new ItemArmorSkyrave (CORDIERITE_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetCordierite");
    public static final Item CORDIERITE_CHESTPLATE= new ItemArmorSkyrave (CORDIERITE_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplateCordierite");
    public static final Item CORDIERITE_LEGGINGS= new ItemArmorSkyrave (CORDIERITE_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsCordierite");
    public static final Item CORDIERITE_BOOTS= new ItemArmorSkyrave (CORDIERITE_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsCordierite");
    public static final Item GARNET_HELMET= new ItemArmorSkyrave (GARNET_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetGarnet");
    public static final Item GARNET_CHESTPLATE= new ItemArmorSkyrave (GARNET_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplateGarnet");
    public static final Item GARNET_LEGGINGS= new ItemArmorSkyrave (GARNET_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsGarnet");
    public static final Item GARNET_BOOTS= new ItemArmorSkyrave (GARNET_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsGarnet");
    public static final Item SAPPHIRE_HELMET= new ItemArmorSkyrave (SAPPHIRE_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetSapphire");
    public static final Item SAPPHIRE_CHESTPLATE= new ItemArmorSkyrave (SAPPHIRE_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplateSapphire");
    public static final Item SAPPHIRE_LEGGINGS= new ItemArmorSkyrave (SAPPHIRE_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsSapphire");
    public static final Item SAPPHIRE_BOOTS= new ItemArmorSkyrave (SAPPHIRE_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsSapphire");
    public static final Item RUBY_HELMET= new ItemArmorSkyrave (RUBY_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetRuby");
    public static final Item RUBY_CHESTPLATE= new ItemArmorSkyrave (RUBY_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplateRuby");
    public static final Item RUBY_LEGGINGS= new ItemArmorSkyrave (RUBY_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsRuby");
    public static final Item RUBY_BOOTS= new ItemArmorSkyrave (RUBY_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsRuby");
    public static final Item EMERALD_HELMET= new ItemArmorSkyrave (EMERALD_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetEmerald");
    public static final Item EMERALD_CHESTPLATE= new ItemArmorSkyrave (EMERALD_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplateEmerald");
    public static final Item EMERALD_LEGGINGS= new ItemArmorSkyrave (EMERALD_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsEmerald");
    public static final Item EMERALD_BOOTS= new ItemArmorSkyrave (EMERALD_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsEmerald");
    public static final Item PLATINUM_HELMET= new ItemArmorSkyrave (PLATINUM_ARMOR_MATERIAL,0,0).setUnlocalizedName("helmetPlatinum");
    public static final Item PLATINUM_CHESTPLATE= new ItemArmorSkyrave (PLATINUM_ARMOR_MATERIAL,0,1).setUnlocalizedName("chestplatePlatinum");
    public static final Item PLATINUM_LEGGINGS= new ItemArmorSkyrave (PLATINUM_ARMOR_MATERIAL,0,2).setUnlocalizedName("leggingsPlatinum");
    public static final Item PLATINUM_BOOTS= new ItemArmorSkyrave (PLATINUM_ARMOR_MATERIAL,0,3).setUnlocalizedName("bootsPlatinum");





    public static void registerItems() {


        Skyrave.proxy.registerItem(AMBER_INGOT, "amber_ingot");
        Skyrave.proxy.registerItem(AMETHYST_INGOT, "amethyst_ingot");
        Skyrave.proxy.registerItem(BERYL_INGOT, "beryl_ingot");
        Skyrave.proxy.registerItem(BRONZE_INGOT, "bronze_ingot");
        Skyrave.proxy.registerItem(CITRINE_INGOT, "citrine_ingot");
        Skyrave.proxy.registerItem(COPPER_INGOT, "copper_ingot");
        Skyrave.proxy.registerItem(CORDIERITE_INGOT, "cordierite_ingot");
        Skyrave.proxy.registerItem(GARNET_INGOT, "garnet_ingot");
        Skyrave.proxy.registerItem(PERIDOT_INGOT, "peridot_ingot");
        Skyrave.proxy.registerItem(PLATINUM_INGOT, "platinum_ingot");
        Skyrave.proxy.registerItem(RUBY_INGOT, "ruby_ingot");
        Skyrave.proxy.registerItem(SAPPHIRE_INGOT, "sapphire_ingot");
        Skyrave.proxy.registerItem(SILVER_INGOT, "silver_ingot");
        Skyrave.proxy.registerItem(TANZANITE_INGOT, "tanzanite_ingot");
        Skyrave.proxy.registerItem(TIN_INGOT, "tin_ingot");
        Skyrave.proxy.registerItem(TOPAZ_INGOT, "topaz_ingot");
        Skyrave.proxy.registerItem(TOURMALINE_INGOT, "tourmaline_ingot");
        Skyrave.proxy.registerItem(ZIRCON_INGOT, "zircon_ingot");

        Skyrave.proxy.registerItem(SHAVED_ICE, "shaved_ice");
        Skyrave.proxy.registerItem(DOUGH, "dough");
        Skyrave.proxy.registerItem(WEED, "weed");

        Skyrave.proxy.registerItem(GRAPE_SEEDS, "grape_seeds");
        Skyrave.proxy.registerItem(PINEAPPLE_SEEDS, "pineapple_seeds");
        Skyrave.proxy.registerItem(CORN_SEEDS, "corn_seeds");
        Skyrave.proxy.registerItem(CUCUMBER_SEEDS, "cucumber_seeds");
        Skyrave.proxy.registerItem(ONION_SEEDS, "onion_seeds");
        Skyrave.proxy.registerItem(RADISH_SEEDS, "radish_seeds");
        Skyrave.proxy.registerItem(SALAD_SEEDS, "salad_seeds");
        Skyrave.proxy.registerItem(TOMATO_SEEDS, "tomato_seeds");

        Skyrave.proxy.registerItem(PURPLE_GRAPES, "purple_grapes");
        Skyrave.proxy.registerItem(PINEAPPLE, "pineapple");
        Skyrave.proxy.registerItem(CORN, "corn");
        Skyrave.proxy.registerItem(CUCUMBER, "cucumber");
        Skyrave.proxy.registerItem(ONION, "onion");
        Skyrave.proxy.registerItem(RADISH, "radish");
        Skyrave.proxy.registerItem(SALAD, "salad");
        Skyrave.proxy.registerItem(TOMATO, "tomato");
        Skyrave.proxy.registerItem(GREEN_GRAPES, "green_grapes");
        Skyrave.proxy.registerItem(APPLE_PIE, "apple_pie");
        Skyrave.proxy.registerItem(BACON_RAW, "bacon_raw");
        Skyrave.proxy.registerItem(BACON_COOKED, "bacon_cooked");
        Skyrave.proxy.registerItem(BANANA, "banana");
        Skyrave.proxy.registerItem(BLUEBERRY, "blueberry");
        Skyrave.proxy.registerItem(SLICE_OF_BREAD, "slice_of_bread");
        Skyrave.proxy.registerItem(BUTTER, "butter");
        Skyrave.proxy.registerItem(CARAMEL, "caramel");
        Skyrave.proxy.registerItem(CHEESE, "cheese");
        Skyrave.proxy.registerItem(CHERRY, "cherry");
        Skyrave.proxy.registerItem(CHILLI, "chilli");
        Skyrave.proxy.registerItem(CHOCOLATE, "chocolate");
        Skyrave.proxy.registerItem(COCONUT, "coconut");
        Skyrave.proxy.registerItem(DONUT, "donut");
        Skyrave.proxy.registerItem(FLOUR, "flour");
        Skyrave.proxy.registerItem(GARLIC, "garlic");
        Skyrave.proxy.registerItem(BANANA_ICE_CREAM, "banana_ice_cream");
        Skyrave.proxy.registerItem(CHERRY_ICE_CREAM, "cherry_ice_cream");
        Skyrave.proxy.registerItem(CHOCOLATE_ICE_CREAM, "chocolate_ice_cream");
        Skyrave.proxy.registerItem(CRANBERRY_ICE_CREAM, "cranberry_ice_cream");
        Skyrave.proxy.registerItem(GREEN_GRAPE_ICE_CREAM, "green_grape_ice_cream");
        Skyrave.proxy.registerItem(KIWI_ICE_CREAM, "kiwi_ice_cream");
        Skyrave.proxy.registerItem(LEMON_ICE_CREAM, "lemon_ice_cream");
        Skyrave.proxy.registerItem(LIME_ICE_CREAM, "lime_ice_cream");
        Skyrave.proxy.registerItem(MANGO_ICE_CREAM, "mango_ice_cream");
        Skyrave.proxy.registerItem(ORANGE_ICE_CREAM, "orange_ice_cream");
        Skyrave.proxy.registerItem(PEER_ICE_CREAM, "peer_ice_cream");
        Skyrave.proxy.registerItem(PINEAPPLE_ICE_CREAM, "pineapple_ice_cream");
        Skyrave.proxy.registerItem(PISTACHIO_ICE_CREAM, "pistachio_ice_cream");
        Skyrave.proxy.registerItem(PURPLE_GRAPE_ICE_CREAM, "purple_grape_ice_cream");
        Skyrave.proxy.registerItem(RAISIN_ICE_CREAM, "raisin_ice_cream");
        Skyrave.proxy.registerItem(RASPBERRY_ICE_CREAM, "raspberry_ice_cream");
        Skyrave.proxy.registerItem(STRAWBERRY_ICE_CREAM, "strawberry_ice_cream");
        Skyrave.proxy.registerItem(BANANA_LOLLIPOP, "banana_lollipop");
        Skyrave.proxy.registerItem(CHERRY_LOLLIPOP, "cherry_lollipop");
        Skyrave.proxy.registerItem(CHOCOLATE_LOLLIPOP, "chocolate_lollipop");
        Skyrave.proxy.registerItem(CRANBERRY_LOLLIPOP, "cranberry_lollipop");
        Skyrave.proxy.registerItem(GREEN_GRAPE_LOLLIPOP, "green_grape_lollipop");
        Skyrave.proxy.registerItem(KIWI_LOLLIPOP, "kiwi_lollipop");
        Skyrave.proxy.registerItem(LEMON_LOLLIPOP, "lemon_lollipop");
        Skyrave.proxy.registerItem(LIME_LOLLIPOP, "lime_lollipop");
        Skyrave.proxy.registerItem(MANGO_LOLLIPOP, "mango_lollipop");
        Skyrave.proxy.registerItem(ORANGE_LOLLIPOP, "orange_lollipop");
        Skyrave.proxy.registerItem(PEER_LOLLIPOP, "peer_lollipop");
        Skyrave.proxy.registerItem(PINEAPPLE_LOLLIPOP, "pineapple_lollipop");
        Skyrave.proxy.registerItem(PISTACHIO_LOLLIPOP, "pistachio_lollipop");
        Skyrave.proxy.registerItem(PURPLE_GRAPE_LOLLIPOP, "purple_grape_lollipop");
        Skyrave.proxy.registerItem(RAISIN_LOLLIPOP, "raisin_lollipop");
        Skyrave.proxy.registerItem(RASPBERRY_LOLLIPOP, "raspberry_lollipop");
        Skyrave.proxy.registerItem(STRAWBERRY_LOLLIPOP, "strawberry_lollipop");
        Skyrave.proxy.registerItem(CARAMEL_APPLE, "caramel_apple");
        Skyrave.proxy.registerItem(RICE, "rice");
        Skyrave.proxy.registerItem(FISH_EGGS, "fish_eggs");
        Skyrave.proxy.registerItem(BOILED_EGG, "boiled_egg");
        Skyrave.proxy.registerItem(DAIKON_OSHINKO_MAKI, "daikon_oshinko_maki");
        Skyrave.proxy.registerItem(EGG_ROLL_SUSHI, "egg_roll_sushi");
        Skyrave.proxy.registerItem(EGGPLANT, "eggplant");
        Skyrave.proxy.registerItem(MAGURO_NIGIRI_WASABI, "maguro_nigiri_wasabi");
        Skyrave.proxy.registerItem(MAKI, "maki");
        Skyrave.proxy.registerItem(MANGO_SUSHI, "mango_sushi");
        Skyrave.proxy.registerItem(MAGURO_NIGIRI, "maguro_nigiri");
        Skyrave.proxy.registerItem(NIGIRI, "nigiri");
        Skyrave.proxy.registerItem(NIGIRI_WASABI, "nigiri_wasabi");
        Skyrave.proxy.registerItem(ONIGIRI, "onigiri");
        Skyrave.proxy.registerItem(ROLL, "roll");
        Skyrave.proxy.registerItem(TEKKAMAKI, "tekkamaki");
        Skyrave.proxy.registerItem(TORO_NIGIRI_TEIYAKI, "toro_nigiri_teiyaki");
        Skyrave.proxy.registerItem(WASABI, "wasabi");
        Skyrave.proxy.registerItem(TUNA, "tuna");
        Skyrave.proxy.registerItem(RED_TUNA, "red_tuna");
        Skyrave.proxy.registerItem(SASHI_SUSHI, "sashi_sushi");
        Skyrave.proxy.registerItem(STRAWBERRY, "strawberry");
        Skyrave.proxy.registerItem(SHRIMP, "shrimp");
        Skyrave.proxy.registerItem(BOWL_OF_SALAD, "bowl_of_salad");
        Skyrave.proxy.registerItem(SALT, "salt");
        Skyrave.proxy.registerItem(PEPPER, "pepper");
        Skyrave.proxy.registerItem(KIWI, "kiwi");
        Skyrave.proxy.registerItem(LEMON, "lemon");
        Skyrave.proxy.registerItem(LIME, "lime");
        Skyrave.proxy.registerItem(MANGO, "mango");
        Skyrave.proxy.registerItem(PEER, "peer");
        Skyrave.proxy.registerItem(UNCOOKED_CALAMARI, "uncooked_calamari");
        Skyrave.proxy.registerItem(COOKED_CALAMARI, "cooked_calamari");
        Skyrave.proxy.registerItem(SQUID, "squid");
        Skyrave.proxy.registerItem(GELATIN, "gelatin");
        Skyrave.proxy.registerItem(GRILLED_CORN, "grilled_corn");
        Skyrave.proxy.registerItem(CONE, "cone");
        Skyrave.proxy.registerItem(CHEESEBURGER, "cheeseburger");
        Skyrave.proxy.registerItem(HOTDOG, "hotdog");
        Skyrave.proxy.registerItem(MUSTARD, "mustard");
        Skyrave.proxy.registerItem(SAUSAGE, "sausage");
        Skyrave.proxy.registerItem(CRANBERRY, "cranberry");
        Skyrave.proxy.registerItem(ORANGE, "orange");
        Skyrave.proxy.registerItem(PISTACHIO, "pistachio");
        Skyrave.proxy.registerItem(RAISIN, "raisin");
        Skyrave.proxy.registerItem(RASPBERRY, "raspberry");



        Skyrave.proxy.registerItem(BRONZE_PICKAXE, "bronze_pickaxe");
        Skyrave.proxy.registerItem(AMETHYST_PICKAXE, "amethyst_pickaxe");
        Skyrave.proxy.registerItem(BERYL_PICKAXE, "beryl_pickaxe");
        Skyrave.proxy.registerItem(AMBER_PICKAXE, "amber_pickaxe");
        Skyrave.proxy.registerItem(TANZANITE_PICKAXE, "tanzanite_pickaxe");
        Skyrave.proxy.registerItem(PERIDOT_PICKAXE, "peridot_pickaxe");
        Skyrave.proxy.registerItem(SILVER_PICKAXE, "silver_pickaxe");
        Skyrave.proxy.registerItem(TOURMALINE_PICKAXE, "tourmaline_pickaxe");
        Skyrave.proxy.registerItem(ZIRCON_PICKAXE, "zircon_pickaxe");
        Skyrave.proxy.registerItem(TOPAZ_PICKAXE, "topaz_pickaxe");
        Skyrave.proxy.registerItem(CITRINE_PICKAXE, "citrine_pickaxe");
        Skyrave.proxy.registerItem(CORDIERITE_PICKAXE, "cordierite_pickaxe");
        Skyrave.proxy.registerItem(GARNET_PICKAXE, "garnet_pickaxe");
        Skyrave.proxy.registerItem(SAPPHIRE_PICKAXE, "sapphire_pickaxe");
        Skyrave.proxy.registerItem(RUBY_PICKAXE, "ruby_pickaxe");
        Skyrave.proxy.registerItem(EMERALD_PICKAXE, "emerald_pickaxe");
        Skyrave.proxy.registerItem(PLATINUM_PICKAXE, "platinum_pickaxe");

        Skyrave.proxy.registerItem(BRONZE_HOE, "bronze_hoe");
        Skyrave.proxy.registerItem(AMETHYST_HOE, "amethyst_hoe");
        Skyrave.proxy.registerItem(BERYL_HOE, "beryl_hoe");
        Skyrave.proxy.registerItem(AMBER_HOE, "amber_hoe");
        Skyrave.proxy.registerItem(TANZANITE_HOE, "tanzanite_hoe");
        Skyrave.proxy.registerItem(PERIDOT_HOE, "peridot_hoe");
        Skyrave.proxy.registerItem(SILVER_HOE, "silver_hoe");
        Skyrave.proxy.registerItem(TOURMALINE_HOE, "tourmaline_hoe");
        Skyrave.proxy.registerItem(ZIRCON_HOE, "zircon_hoe");
        Skyrave.proxy.registerItem(TOPAZ_HOE, "topaz_hoe");
        Skyrave.proxy.registerItem(CITRINE_HOE, "citrine_hoe");
        Skyrave.proxy.registerItem(CORDIERITE_HOE, "cordierite_hoe");
        Skyrave.proxy.registerItem(GARNET_HOE, "garnet_hoe");
        Skyrave.proxy.registerItem(SAPPHIRE_HOE, "sapphire_hoe");
        Skyrave.proxy.registerItem(RUBY_HOE, "ruby_hoe");
        Skyrave.proxy.registerItem(EMERALD_HOE, "emerald_hoe");
        Skyrave.proxy.registerItem(PLATINUM_HOE, "platinum_hoe");

        Skyrave.proxy.registerItem(BRONZE_SWORD, "bronze_sword");
        Skyrave.proxy.registerItem(AMETHYST_SWORD, "amethyst_sword");
        Skyrave.proxy.registerItem(BERYL_SWORD, "beryl_sword");
        Skyrave.proxy.registerItem(AMBER_SWORD, "amber_sword");
        Skyrave.proxy.registerItem(TANZANITE_SWORD, "tanzanite_sword");
        Skyrave.proxy.registerItem(PERIDOT_SWORD, "peridot_sword");
        Skyrave.proxy.registerItem(SILVER_SWORD, "silver_sword");
        Skyrave.proxy.registerItem(TOURMALINE_SWORD, "tourmaline_sword");
        Skyrave.proxy.registerItem(ZIRCON_SWORD, "zircon_sword");
        Skyrave.proxy.registerItem(TOPAZ_SWORD, "topaz_sword");
        Skyrave.proxy.registerItem(CITRINE_SWORD, "citrine_sword");
        Skyrave.proxy.registerItem(CORDIERITE_SWORD, "cordierite_sword");
        Skyrave.proxy.registerItem(GARNET_SWORD, "garnet_sword");
        Skyrave.proxy.registerItem(SAPPHIRE_SWORD, "sapphire_sword");
        Skyrave.proxy.registerItem(RUBY_SWORD, "ruby_sword");
        Skyrave.proxy.registerItem(EMERALD_SWORD, "emerald_sword");
        Skyrave.proxy.registerItem(PLATINUM_SWORD, "platinum_sword");

        Skyrave.proxy.registerItem(BRONZE_AXE, "bronze_axe");
        Skyrave.proxy.registerItem(AMETHYST_AXE, "amethyst_axe");
        Skyrave.proxy.registerItem(BERYL_AXE, "beryl_axe");
        Skyrave.proxy.registerItem(AMBER_AXE, "amber_axe");
        Skyrave.proxy.registerItem(TANZANITE_AXE, "tanzanite_axe");
        Skyrave.proxy.registerItem(PERIDOT_AXE, "peridot_axe");
        Skyrave.proxy.registerItem(SILVER_AXE, "silver_axe");
        Skyrave.proxy.registerItem(TOURMALINE_AXE, "tourmaline_axe");
        Skyrave.proxy.registerItem(ZIRCON_AXE, "zircon_axe");
        Skyrave.proxy.registerItem(TOPAZ_AXE, "topaz_axe");
        Skyrave.proxy.registerItem(CITRINE_AXE, "citrine_axe");
        Skyrave.proxy.registerItem(CORDIERITE_AXE, "cordierite_axe");
        Skyrave.proxy.registerItem(GARNET_AXE, "garnet_axe");
        Skyrave.proxy.registerItem(SAPPHIRE_AXE, "sapphire_axe");
        Skyrave.proxy.registerItem(RUBY_AXE, "ruby_axe");
        Skyrave.proxy.registerItem(EMERALD_AXE, "emerald_axe");
        Skyrave.proxy.registerItem(PLATINUM_AXE, "platinum_axe");

        Skyrave.proxy.registerItem(BRONZE_SHOVEL, "bronze_shovel");
        Skyrave.proxy.registerItem(AMETHYST_SHOVEL, "amethyst_shovel");
        Skyrave.proxy.registerItem(BERYL_SHOVEL, "beryl_shovel");
        Skyrave.proxy.registerItem(AMBER_SHOVEL, "amber_shovel");
        Skyrave.proxy.registerItem(TANZANITE_SHOVEL, "tanzanite_shovel");
        Skyrave.proxy.registerItem(PERIDOT_SHOVEL, "peridot_shovel");
        Skyrave.proxy.registerItem(SILVER_SHOVEL, "silver_shovel");
        Skyrave.proxy.registerItem(TOURMALINE_SHOVEL, "tourmaline_shovel");
        Skyrave.proxy.registerItem(ZIRCON_SHOVEL, "zircon_shovel");
        Skyrave.proxy.registerItem(TOPAZ_SHOVEL, "topaz_shovel");
        Skyrave.proxy.registerItem(CITRINE_SHOVEL, "citrine_shovel");
        Skyrave.proxy.registerItem(CORDIERITE_SHOVEL, "cordierite_shovel");
        Skyrave.proxy.registerItem(GARNET_SHOVEL, "garnet_shovel");
        Skyrave.proxy.registerItem(SAPPHIRE_SHOVEL, "sapphire_shovel");
        Skyrave.proxy.registerItem(RUBY_SHOVEL, "ruby_shovel");
        Skyrave.proxy.registerItem(EMERALD_SHOVEL, "emerald_shovel");
        Skyrave.proxy.registerItem(PLATINUM_SHOVEL, "platinum_shovel");

        Skyrave.proxy.registerItem(BRONZE_HELMET, "bronze_helmet");
        Skyrave.proxy.registerItem(BRONZE_CHESTPLATE, "bronze_chestplate");
        Skyrave.proxy.registerItem(BRONZE_LEGGINGS, "bronze_leggings");
        Skyrave.proxy.registerItem(BRONZE_BOOTS, "bronze_boots");
        Skyrave.proxy.registerItem(AMETHYST_HELMET, "amethyst_helmet");
        Skyrave.proxy.registerItem(AMETHYST_CHESTPLATE, "amethyst_chestplate");
        Skyrave.proxy.registerItem(AMETHYST_LEGGINGS, "amethyst_leggings");
        Skyrave.proxy.registerItem(AMETHYST_BOOTS, "amethyst_boots");
        Skyrave.proxy.registerItem(BERYL_HELMET, "beryl_helmet");
        Skyrave.proxy.registerItem(BERYL_CHESTPLATE, "beryl_chestplate");
        Skyrave.proxy.registerItem(BERYL_LEGGINGS, "beryl_leggings");
        Skyrave.proxy.registerItem(BERYL_BOOTS, "beryl_boots");
        Skyrave.proxy.registerItem(AMBER_HELMET, "amber_helmet");
        Skyrave.proxy.registerItem(AMBER_CHESTPLATE, "amber_chestplate");
        Skyrave.proxy.registerItem(AMBER_LEGGINGS, "amber_leggings");
        Skyrave.proxy.registerItem(TANZANITE_HELMET, "tanzanite_helmet");
        Skyrave.proxy.registerItem(TANZANITE_CHESTPLATE, "tanzanite_chestplate");
        Skyrave.proxy.registerItem(TANZANITE_LEGGINGS, "tanzanite_leggings");
        Skyrave.proxy.registerItem(TANZANITE_BOOTS, "tanzanite_boots");
        Skyrave.proxy.registerItem(PERIDOT_HELMET, "peridot_helmet");
        Skyrave.proxy.registerItem(PERIDOT_CHESTPLATE, "peridot_chestplate");
        Skyrave.proxy.registerItem(PERIDOT_LEGGINGS, "peridot_leggings");
        Skyrave.proxy.registerItem(PERIDOT_BOOTS, "peridot_boots");
        Skyrave.proxy.registerItem(SILVER_HELMET, "silver_helmet");
        Skyrave.proxy.registerItem(SILVER_CHESTPLATE, "silver_chestplate");
        Skyrave.proxy.registerItem(SILVER_LEGGINGS, "silver_leggings");
        Skyrave.proxy.registerItem(SILVER_BOOTS, "silver_boots");
        Skyrave.proxy.registerItem(TOURMALINE_HELMET, "tourmaline_helmet");
        Skyrave.proxy.registerItem(TOURMALINE_CHESTPLATE, "tourmaline_chestplate");
        Skyrave.proxy.registerItem(TOURMALINE_LEGGINGS, "tourmaline_leggings");
        Skyrave.proxy.registerItem(TOURMALINE_BOOTS, "tourmaline_boots");
        Skyrave.proxy.registerItem(ZIRCON_HELMET, "zircon_helmet");
        Skyrave.proxy.registerItem(ZIRCON_CHESTPLATE, "zircon_chestplate");
        Skyrave.proxy.registerItem(ZIRCON_LEGGINGS, "zircon_leggings");
        Skyrave.proxy.registerItem(ZIRCON_BOOTS, "zircon_boots");
        Skyrave.proxy.registerItem(TOPAZ_HELMET, "topaz_helmet");
        Skyrave.proxy.registerItem(TOPAZ_CHESTPLATE, "topaz_chestplate");
        Skyrave.proxy.registerItem(TOPAZ_LEGGINGS, "topaz_leggings");
        Skyrave.proxy.registerItem(TOPAZ_BOOTS, "topaz_boots");
        Skyrave.proxy.registerItem(CITRINE_HELMET, "citrine_helmet");
        Skyrave.proxy.registerItem(CITRINE_CHESTPLATE, "citrine_chestplate");
        Skyrave.proxy.registerItem(CITRINE_LEGGINGS, "citrine_leggings");
        Skyrave.proxy.registerItem(CITRINE_BOOTS, "citrine_boots");
        Skyrave.proxy.registerItem(CORDIERITE_HELMET, "cordierite_helmet");
        Skyrave.proxy.registerItem(CORDIERITE_CHESTPLATE, "cordierite_chestplate");
        Skyrave.proxy.registerItem(CORDIERITE_LEGGINGS, "cordierite_leggings");
        Skyrave.proxy.registerItem(CORDIERITE_BOOTS, "cordierite_boots");
        Skyrave.proxy.registerItem(GARNET_HELMET, "garnet_helmet");
        Skyrave.proxy.registerItem(GARNET_CHESTPLATE, "garnet_chestplate");
        Skyrave.proxy.registerItem(GARNET_LEGGINGS, "garnet_leggings");
        Skyrave.proxy.registerItem(GARNET_BOOTS, "garnet_boots");
        Skyrave.proxy.registerItem(SAPPHIRE_HELMET, "sapphire_helmet");
        Skyrave.proxy.registerItem(SAPPHIRE_CHESTPLATE, "sapphire_chestplate");
        Skyrave.proxy.registerItem(SAPPHIRE_LEGGINGS, "sapphire_leggings");
        Skyrave.proxy.registerItem(SAPPHIRE_BOOTS, "sapphire_boots");
        Skyrave.proxy.registerItem(RUBY_HELMET, "ruby_helmet");
        Skyrave.proxy.registerItem(RUBY_CHESTPLATE, "ruby_chestplate");
        Skyrave.proxy.registerItem(RUBY_LEGGINGS, "ruby_leggings");
        Skyrave.proxy.registerItem(RUBY_BOOTS, "ruby_boots");
        Skyrave.proxy.registerItem(EMERALD_HELMET, "emerald_helmet");
        Skyrave.proxy.registerItem(EMERALD_CHESTPLATE, "emerald_chestplate");
        Skyrave.proxy.registerItem(EMERALD_LEGGINGS, "emerald_leggings");
        Skyrave.proxy.registerItem(EMERALD_BOOTS, "emerald_boots");
        Skyrave.proxy.registerItem(PLATINUM_HELMET, "platinum_helmet");
        Skyrave.proxy.registerItem(PLATINUM_CHESTPLATE, "platinum_chestplate");
        Skyrave.proxy.registerItem(PLATINUM_LEGGINGS, "platinum_leggings");
        Skyrave.proxy.registerItem(PLATINUM_BOOTS, "platinum_boots");

    }
}
